package com.marco.customer.dal;
// Generated 06/09/2016 09:29:57 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Customers generated by hbm2java
 */
public class Customers extends BaseDO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -989748734665688893L;
	private Integer id;
	private String firstName;
	private String lastName;

	public Customers() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
