CREATE DATABASE IF NOT EXISTS `customer`;
use customer;
CREATE TABLE IF NOT EXISTS `customers` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) DEFAULT NULL,
	`last_name` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8